version: "2"

linters:
  enable:
    - misspell
  
  settings:
    govet:
      disable:
        - composites
    
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (io/fs.File).Close
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - io.Copy(os.Stderr)
        - (*io.PipeReader).Close
        - (*io.PipeWriter).Close
        - (*github.com/MatusOllah/resona/playback.Context).Close

    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1023
        - -QF1008
        - -QF1011

    misspell:
      locale: US
