version: "2"

linters:
  enable:
    - misspell
  
  settings:
    govet:
      disable:
        - composites
    
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (io/fs.File).Close
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - io.Copy(os.Stderr)

    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1023
        - -QF1008

    misspell:
      locale: US
